name: CI with shared data

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  use-data:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      
      - name: Restore shared data cache
        id: cache-data
        uses: actions/cache@v4
        with:
          path: data/
          key: shared-data-${{ runner.os }}-${{ hashFiles('.github/scripts/download_data.sh') }}
          restore-keys: |
            shared-data-${{ runner.os }}-

      - name: Check if cache hit
        run: |
          if [ "${{ steps.cache-data.outputs.cache-hit }}" != "true" ]; then
            echo "Cache miss, failing the job."
            exit 1
          fi
      - name: Use the data
        run: |
          ls data/
          # …your tests or build steps here
